apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: podinfo
spec:
  releaseName: redis
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "11.3.4"
  interval: 1h0m0s
  values:
    cluster:
      enabled: false
    master:
      persistence:
        enabled: false
    auth:
      enabled: true
      existingSecret: "redis"
      existingSecretPasswordKey: "password"
