apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: podinfo
spec:
  encryptedData:
    password: AgBxU0WlSyRjGJsa7JyA9ZCCfJjTU4jxXUrZ0JLOe0tzuVEwTN2gYF5aOeLAjIei4ibxKkQdlV/Ohy9FjwJGI+MEaf0ZX7mgYRjPbnYxULirETjpGF1xL6jnMKdsXqfO2Ks3Hr/DLpPzwpbv/YZfzXTZQe8FWyltm5irrpRxYP3d6JCXNvQyVUDyCn98kvrlvs2LSSEwx2giNAVqBF3mYtECg4Y9//1l6Ctffjo2TidsWO5nwvBogNScvayukdgl9GXv0lBXhYgaDVZd8ChLqMbNTmEonpCGurCWt8Ye2noTWP47GiGxF7yQcxyPVTlb5iRiH+OAQuX+dsynn+mfTF9zjrLLO3X+/Z+E9a+LKlb788YdJVvbClQ29xC+Dchfev+J5uX0hvjjXGobNi5V9NYyOuxM4Q6jlOxR7oPp2giHlAdHvlv1HpCXhFPf/fBXqmxwARPx6e0nkX+ONudAjQpufZGXs04Nq1RAkQFkAAZhfvUQoSkgjtBOoCO06ZyyaybbzUZTQb+VRFBX4QTvrCDxr5LWEElkrJwazwOFYTK5/6nUN/5bkGnoVFP20gtdA3TfDDVbdtg6WZtdPbk+EyHdLLNYWdOnsY+bPzMlDuIUQxouwSAR0OBbglQ+TZBusHHrQ2NnYBEBnJrt0YI9yRHaZj1RD4zD6vOPQYMIF1YFvckSIYVWhzcvWKkvWoUMQteZEo0uSVM8
  template:
    data: null
    metadata:
      name: redis
      namespace: podinfo
