apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: podinfo
spec:
  encryptedData:
    password: AgCVbEaJkGvnssQpGFYzFoDto0ZEBT9Xb99kn0EdKacfgnPW7o79FnvhC1jggxFUzwey1MPcQqTpZ6YYecJGSSMNik5vHcRCMa95Vcp1WkuEi3ZxCsvhiIOjoY0BbaZH65+bfxi0PKZbBad5AMI2eQTdU5atwGJ3rC1LpMD3HX2GgTj1wfUoXOMgAmi0d9vmaKluxQcfR7LUFhQogIgSxlrAPPuF0/0C2r2oyhqJiqfVGYGKPjHHhODvyDplHPrDkNZnsbDmjqtf1aPDuj/kQK/uT2jPSdDM2iLSvMRm9DNWIUfWanGD4AynrqURS1oozQM8PZyvX2DeI6vla9gqhSXwUnHyu5N4t5lvFUvZ9mH8B26EMESk/tfQOVBQVv0Lf81hw7DayFemZBpVjgfNW04fLTCd7oxyojwL/e5BMdzK8NMU4io7LQPY0ks+gTJSbfGChiL6lbALPd4lEJNucp8T/KBog0vHoHAfergf24NnCl1/pY+pU8HTj14FyV7wWEa7lVy7MiAE7ZbhYDtoutHdaXiiBF6AJsh54IvTQR373ZJwgMru8G5qzuTkrr7JRv3NHrM2G2S5qMMplB3xoE8ORJXkkvBUeoMUg5UE9pWIL5C1zfXbcBZKn2T0/sojgbHSLIZyuBuq04l4K9vtHPbEjoitKR1jJE/DCPimuzByu/pVqHM42ngErSnXZJpyNj6LTKd+oIVo
  template:
    data: null
    metadata:
      name: redis
      namespace: podinfo
