apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: podinfo
spec:
  encryptedData:
    password: AgAXr1pe9CSBosadFo2G7C8ZIfE3X6mt6Oe1CYEoru0ue9Vj2WesDVkS5lMAUH6CdzPhZmYKY61KERrtwmp9rHvBJnNPM1C98UZY5LGaVplUJSGZXjVWbyQ0udbLuziaBGlBYXK+PxGkTR3cYvfrAySj8lD9EC5aE0QJZTPPLsaIZx64Z0Su+YBS0t8R7yRQrrArQKLPFYLayzwCaBQZHNEzKI4R10EEi7kxzSq2iO1cKB+NwYXWIOJLKqmGBcJpr6YwnjvdbD46yTQYpcoN4vAcdIjxnysUH/kjiFmJBJ9nBmBgXjLab5yCoBREf7JlPCO3JJtECgi2XmdwphrTMQyW9vPKc0v1LbDsc33V/1iEIda9RQiw+Qy5+D1jU/aoXOWF5FPiPJcHJwG66aNu3hRUq9WlpvYxGUBN9HH8yBIxkdmAVzXSqlCuaey+6A+x2gmTsCH1RmcTI5WE3f0/hxmCv0/LcmHOWq/N4EltBMLdwcrW/N+j0D8MAewCeK5+ST0Sa9XCZQd34HgOcYp582SQzbSFyrnB+d28vN2Uv5IYQ8fLKYmNPMYrln38YffnIp0ZGoHjhnBiPNPMa7og4OG+iERWmjzTc+xSGKdc0ez8yYvmEOJrcNwxilpigNSxwS6TG10NB2NdDC4LJZrpAT2p7KNpJjjEkf9idw5uAR4E59jJZoWia2pZb/S6Ebs7uwnz0EdB1Rsg
