apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
spec:
  encryptedData:
    password: AgATjgXhyXXT1aeub5LCYOM15iteWo6PzW4qiNKebknxvjS8caqRxbQTMqWeTS5q6xOVo2PRnOGZcTi6Z3cwhcc2WaV+PQ0Z3/pi4qHwsclAGBEbhAo1m2V6+Qkk5UngTbT5gABRsqASi38qPB9iPUMCAdtGj1gT8LRwR2huHjcxjjhW5lZUbItwK9+NVWMo5CsCDIjFEYR6kMFqikpvMuLDcUmAKfH1sbFlG4yQBTzPWYIuGgtgVgtKsV3gyrJnX4PVQ741IfV8ClHvWIrT+SBPhBXbeVkVhvqGJpgJwWavb0SpVs73RK6BNsUo6wz6lk8gfMJTaPO58xfOWFOpOaZh6LfarIkLjbLjBe1hzpD9BR4S3yc9yiepm2A2c7Qbgnt/b4e1qVbLL2tz1/jow9OJcnKskPWWhXFHUyKkJn47esgJmNS8z3OgLKQSjHwkVhPpFib9s9SdTibNdEDrvdg06PlS9k4eEqbuQxDJvgAWikQZ9Q5niac9pmJrg5Put+z0t8xq1zhXk+vCoQRq3+WCyycUfeLO7DYTf5vbg1C0utC2+F0qXhE2j1eGpP6pOKGEzZgpZTps00w9aVU6WK8jpdM/2khzYfl9u/bdOiFF3bcDiTUVh8ymIzmoLVibBmV7aGMfaj75O3T7K9UJFjeFEzlrXA0gWlevq6cb2FVL/4nCNYcPOALwcabdIMRXCQwGNoLB5uI/
  template:
    data: null
    metadata:
      name: redis
      namespace: podinfo
