# Default values
# https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml
cluster:
  enabled: false
master:
  persistence:
    enabled: false
auth:
  enabled: true
  existingSecret: "redis"
  existingSecretPasswordKey: "password"
